language: python
python:
- '3.5'
- '3.6'
notifications:
  email: false
env:
  matrix:
  - TEST="PYTEST"
  - TEST="FLAKE8"
install:
# development versions
- travis_retry pip install -e git+git://github.com/RI-Imaging/qpimage.git
- travis_retry pip install -e git+git://github.com/RI-Imaging/qpformat.git
- travis_retry pip install -e git+git://github.com/RI-Imaging/qpsphere.git
# everything else
- travis_retry pip install --no-deps -e .
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- pip freeze
script:
- set -ev
- if [ "${TEST}" == "PYTEST" ]; then
       coverage run --source=drymass ./setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 drymass;
       flake8 examples;
       flake8 tests;
  fi;
